### PR TITLE
Adding the data_names params in mx.Module

### PR DESCRIPTION
**Pull request by gautamkmr**
Before or while filing an issue please feel free to join our [ slack channel](https://join.slack.com/t/mms-awslabs/shared_invite/enQtNDk4MTgzNDc5NzE4LTBkYTAwMjBjMTVmZTdkODRmYTZkNjdjZGYxZDI0ODhiZDdlM2Y0ZGJiZTczMGY3Njc4MmM3OTQ0OWI2ZDMyNGQ) to get in touch with development team, ask questions, find out what's cooking and more!

## Issue #, if available:
Adding data_names params in mx.mod.Module() vision examples.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/mxnet/module/module.py", line 95, in __init__
    _check_input_names(symbol, data_names, "data", True)
  File "/usr/local/lib/python3.6/site-packages/mxnet/module/base_module.py", line 54, in _check_input_names
    raise ValueError(msg)
ValueError: You created Module with Module(..., data_names=['data']) but input with name 'data' is not found in symbol.list_arguments(). Did you mean one of:
     /conv2d_1_input1
     conv2d_1/kernel1
     conv2d_1/bias1
     conv2d_2/kernel1
     conv2d_2/bias1
     dense_1/kernel1
     dense_1/bias1
     dense_2/kernel1
     dense_2/bias1
 

## Description of changes:
Adding data_names params in mx.mod.Module() vision examples

## Testing done:

**To run CI tests on your changes refer [README.md](https://github.com/awslabs/mxnet-model-server/blob/master/ci/README.md)**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by gautamkmr** [comment]
@vdantu ddavydenko@

**Comment by gautamkmr** [comment]
Tested it manually by running through the example.

**Comment by vdantu** [comment]
The change looks simple enough. But, could you add a little more about why this change is significant, what error you faced etc. Also, you could update the actual python files here https://github.com/awslabs/mxnet-model-server/tree/master/examples/model_service_template

**Comment by vdantu** [comment]
@gautamkmr : would you need any help with updating the python files here? Its a useful change, I would recommend making these changes in the actual source files as well. Also add a short user-experience section in description or README for folks who would want to use this parameter :)

**Comment by gautamkmr** [comment]
I have added the description also all the python files are good just that README had issue,

**Comment by gautamkmr** [comment]
@vdantu

**Pull request merged**
