### PR TITLE
pypi summary

### LINKED ISSUE #378: MMS PyPi package does not have a long_description
MMS PyPi package does not have a long_description, see [here](https://pypi.org/project/mxnet-model-server/)
We need to add one to setup.py.
(reported by @srochel )

@aaronmarkham can you help with writing the long description? check out [MXNet's](https://pypi.org/project/mxnet/) as an example
@vrakesh can you please update it in the code once ready?

Let's please fix this for v0.4

### PR DESCRIPTION
**Pull request by aaronmarkham**
*Issue #*
Fixes #378 

*Description of changes:*
We need a summary for pypi. I wasn't sure what to call it or where to put it, so it's pypi.md for now. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by lupesko** [comment]
@aaronmarkham , you need to add a long_description to setup.py
Here's [an example](http://python-packaging.readthedocs.io/en/latest/metadata.html)

I suggest you update your file to .rst format, rename it to PyPiDescription.rst, and update setup.py per the example above.

Happy to help!

**Comment by vrakesh** [comment]
the codebuild builds the package from the new setup.py, that will be a good test in itself. :)

**Comment by lupesko** [comment]
To test, build locally and upload to TestPyPi
https://packaging.python.org/guides/using-testpypi/

**Comment by aaronmarkham** [comment]
Here's the test package page:
https://test.pypi.org/project/mxnet-model-server/

I made a universal package and uploaded that:
```
Uploading mxnet_model_server-0.3-py2.py3-none-any.whl
Uploading mxnet-model-server-0.3.tar.gz
Uploading mxnet_model_server-0.1.5-py3.6.egg
Uploading mxnet_model_server-0.2-py2.7.egg
Uploading mxnet_model_server-0.2-py3.6.egg
```

Running the install on the test package on Ubuntu looks fine:
```
pip install --index-url https://test.pypi.org/simple/ mxnet-model-server
```
Starting a server works.
However, I don't like the output at the end of the pip install step...
```
Installing collected packages: mxnet
Successfully installed mxnet-0.12.0
```
I had activated the MXNet Conda env on my DLAMI which should have MXNet v1.1. So what did installing MMS do to my conda env with v1.1?
```
(mxnet_p36) ubuntu@ip-172-31-27-229:~$ python
Python 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
>>> mx.__version__
'0.12.0'
>>> 
```
It blew it away. That's not good. That's probably a separate issue, but good to note!

**Comment by aaronmarkham** [comment]
This PR keeps failing CI on "Provisioning". I have tried the retry on it a few times now. Any ideas?

**Comment by lupesko** [comment]
Thanks @aaronmarkham - merged...

**Pull request merged**
